### ISSUE TITLE
builder error: unsupported value

### ISSUE THREAD

**Issue by Flo2410** [JacobLinCool/moodle-rs#3]
Hello, 

I encountered a problem using the ``moodle::api::core::user::set_user_preferences::call`` function.

Running the code below, throws the following error message:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: builder error: unsupported value
```

```rust
let user_id = 18407;
let course_id = "5918";
let visibility = false;

let pref = set_user_preferences::ParamsPreferencesItem {
    name: Some(String::from(format!("block_myoverview_hidden_course_{}", course_id))),
    value: Some(visibility.to_string()),
    userid: Some(user_id),
};

let res = set_user_preferences::call(
    client,
    &mut set_user_preferences::Params {
        preferences: Some(vec![pref]),
    },
)
.await
.unwrap();
```

I would appreciate any help, in case I made a mistake.

**Comment by JacobLinCool** [comment]
It looks like `reqwest::Client.form` can't automatically turn a vector into a form body in the way that Moodle's API expects. Moodle requires parameters to be formatted like `vec[0][a]=val1&vec[0][b]=val2&vec[1][a]=val3&vec[1][b]=val4`, and the `serde_urlencoded` library that `reqwest::Client.form` uses internally doesn't handle this format automatically. However, you can manually create the body for these specific scenarios.

Here's an example that demonstrates this approach:

```rust
let client = MoodleClient::new(&base_url, &token);

let mut params: HashMap<String, String> = HashMap::new();
params.insert("courseid".to_string(), "12345".to_string());
params.insert("options[0][name]".to_string(), "excludecontents".to_string());
params.insert("options[0][value]".to_string(), "1".to_string());

let result = client.post("core_course_get_contents", &params).await;
```

You can find this example at https://github.com/JacobLinCool/moodle-rs/blob/main/moodle/examples/raw-body.rs. (just added)

For future versions, we might consider creating a new trait that converts structs into Moodle-style parameters.

**Comment by Flo2410** [comment]
Thanks for the quick answer.

Yap, this works.
